-- ════════════════════════════════════════════════════════════════
-- RELISH PLATFORM — Suite Schema DDL
-- Migration: 003_suite_schema.sql
-- Source: RELISH_SUITE_SPEC_V2.md Section 4
-- Prerequisite: 002_registry_schema.sql (registry.companies must exist)
-- RLS policies: NOT included here — see 005_rls_and_grants.sql
-- ════════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════════
-- PRODUCTS CATALOGUE
-- product_id on line items is nullable — free-text line items allowed
-- when no catalogue entry exists.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE suite.products (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id      UUID NOT NULL REFERENCES registry.companies(id),
  name            TEXT NOT NULL,
  description     TEXT,
  hsn_code        TEXT,
  default_unit    TEXT DEFAULT 'KG',
  default_price   NUMERIC(15,2),
  currency        TEXT DEFAULT 'INR',
  is_active       BOOLEAN DEFAULT TRUE,
  created_by      UUID REFERENCES auth.users(id),
  created_at      TIMESTAMPTZ DEFAULT now(),
  updated_at      TIMESTAMPTZ DEFAULT now(),
  UNIQUE(company_id, name)
);

CREATE INDEX idx_products_company ON suite.products(company_id);

-- ════════════════════════════════════════════════════════════════
-- DELIVERY ADDRESSES
-- Saved delivery address book per company.
-- delivery_address_id on purchase_orders references this table.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE suite.delivery_addresses (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id      UUID NOT NULL REFERENCES registry.companies(id),
  label           TEXT NOT NULL,          -- 'Panavally Plant', 'Main Office' etc.
  address_line1   TEXT NOT NULL,
  address_line2   TEXT,
  city            TEXT,
  state           TEXT,
  pincode         TEXT,
  country         TEXT DEFAULT 'India',
  is_default      BOOLEAN DEFAULT FALSE,
  is_active       BOOLEAN DEFAULT TRUE,
  created_by      UUID REFERENCES auth.users(id),
  created_at      TIMESTAMPTZ DEFAULT now(),
  UNIQUE(company_id, label)
);

CREATE INDEX idx_delivery_addresses_company ON suite.delivery_addresses(company_id);

-- ════════════════════════════════════════════════════════════════
-- PURCHASE ORDERS
-- vendor_entity_id → registry.entities (live reference)
-- Vendor snapshot fields preserved for document historical integrity.
-- po_number generated by registry.next_cal_sequence().
-- ════════════════════════════════════════════════════════════════
CREATE TABLE suite.purchase_orders (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id              UUID NOT NULL REFERENCES registry.companies(id),
  po_number               TEXT NOT NULL,            -- from registry.next_cal_sequence()
  po_date                 DATE NOT NULL DEFAULT CURRENT_DATE,
  required_date           DATE,
  currency                TEXT NOT NULL DEFAULT 'INR',
  status                  TEXT NOT NULL DEFAULT 'draft'
                            CHECK (status IN (
                              'draft','submitted','pending_approval','approved',
                              'sent','partial','fulfilled','rejected','cancelled'
                            )),
  priority                TEXT DEFAULT 'Normal',
  reference_doc           TEXT,
  department              TEXT,
  notes                   TEXT,

  -- Vendor: live reference to registry.entities
  vendor_entity_id        UUID REFERENCES registry.entities(id),
  -- Vendor snapshot at time of PO (preserves document integrity)
  vendor_name             TEXT,
  vendor_address          TEXT,
  vendor_gstin            TEXT,
  vendor_contact          TEXT,
  vendor_phone            TEXT,
  vendor_email            TEXT,
  vendor_bank_details     TEXT,

  -- Delivery
  delivery_address_id     UUID REFERENCES suite.delivery_addresses(id),
  delivery_address_text   TEXT,             -- snapshot or one-off address
  delivery_date           DATE,
  incoterm                TEXT,
  freight_responsibility  TEXT,
  transport_mode          TEXT,
  packing_instructions    TEXT,
  delivery_instructions   TEXT,

  -- Financials
  subtotal                NUMERIC(15,2) DEFAULT 0,
  discount_percent        NUMERIC(15,2) DEFAULT 0,
  discount_amount         NUMERIC(15,2) DEFAULT 0,
  tax_rate                NUMERIC(15,2) DEFAULT 0,
  tax_amount              NUMERIC(15,2) DEFAULT 0,
  freight_other           NUMERIC(15,2) DEFAULT 0,
  total                   NUMERIC(15,2) DEFAULT 0,

  -- Terms
  payment_terms           TEXT,
  terms_conditions        TEXT,
  authorised_by           TEXT DEFAULT 'Motty Philip',
  internal_remarks        TEXT,

  -- Audit
  created_by              UUID REFERENCES auth.users(id),
  created_at              TIMESTAMPTZ DEFAULT now(),
  updated_at              TIMESTAMPTZ DEFAULT now(),
  UNIQUE(company_id, po_number)
);

CREATE INDEX idx_po_company ON suite.purchase_orders(company_id);
CREATE INDEX idx_po_status  ON suite.purchase_orders(status);
CREATE INDEX idx_po_vendor  ON suite.purchase_orders(vendor_entity_id);

CREATE TABLE suite.po_line_items (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  po_id            UUID NOT NULL REFERENCES suite.purchase_orders(id) ON DELETE CASCADE,
  line_number      INT NOT NULL,
  product_id       UUID REFERENCES suite.products(id),  -- nullable; free-text allowed
  description      TEXT,
  hsn_code         TEXT,
  quantity         NUMERIC(15,3) DEFAULT 0,
  unit             TEXT DEFAULT 'KG',
  unit_price       NUMERIC(15,2) DEFAULT 0,
  discount_percent NUMERIC(5,2) DEFAULT 0,
  amount           NUMERIC(15,2) DEFAULT 0,
  created_at       TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_po_line_items_po ON suite.po_line_items(po_id);

-- ════════════════════════════════════════════════════════════════
-- INVOICES
-- buyer_entity_id → registry.entities (live reference)
-- Full export invoice fields preserved from current Suite.
-- invoice_number generated by registry.next_cal_sequence().
-- ════════════════════════════════════════════════════════════════
CREATE TABLE suite.invoices (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id            UUID NOT NULL REFERENCES registry.companies(id),
  doc_type              TEXT NOT NULL DEFAULT 'proforma'
                          CHECK (doc_type IN (
                            'proforma','commercial','tax_invoice','credit_note'
                          )),
  invoice_number        TEXT NOT NULL,              -- from registry.next_cal_sequence()
  invoice_date          DATE NOT NULL DEFAULT CURRENT_DATE,
  expiry_date           DATE,
  currency              TEXT NOT NULL DEFAULT 'USD',
  status                TEXT NOT NULL DEFAULT 'draft'
                          CHECK (status IN (
                            'draft','sent','accepted','paid','cancelled'
                          )),

  -- Buyer: live reference to registry.entities
  buyer_entity_id       UUID REFERENCES registry.entities(id),
  -- Buyer snapshot at time of invoice
  bill_to_company       TEXT,
  bill_to_address       TEXT,
  bill_to_gstin         TEXT,
  bill_to_contact       TEXT,
  bill_to_phone         TEXT,
  bill_to_email         TEXT,

  -- Shipping
  ship_to_company       TEXT,
  ship_to_address       TEXT,
  notify_party          TEXT,

  -- Logistics
  freight_type          TEXT,
  incoterm              TEXT,
  port_of_loading       TEXT,
  port_of_discharge     TEXT,
  ship_date             DATE,
  delivery_date         DATE,
  vessel                TEXT,
  bl_number             TEXT,
  gross_weight          TEXT,
  net_weight            TEXT,
  cubic_volume          TEXT,
  total_packages        TEXT,
  marks                 TEXT,
  country_of_origin     TEXT,
  final_destination     TEXT,

  -- Financials
  subtotal              NUMERIC(15,2) DEFAULT 0,
  tax_rate              NUMERIC(15,2) DEFAULT 0,
  tax_amount            NUMERIC(15,2) DEFAULT 0,
  freight_other         NUMERIC(15,2) DEFAULT 0,
  total                 NUMERIC(15,2) DEFAULT 0,

  -- Export documentation
  customer_ref          TEXT,
  reason_export         TEXT,
  lc_number             TEXT,
  lc_date               DATE,
  hs_code               TEXT,
  coo_number            TEXT,
  phyto_number          TEXT,

  -- Terms
  payment_terms         TEXT,
  terms_conditions      TEXT,
  bank_details          TEXT,
  declaration           TEXT,
  customs_remarks       TEXT,

  -- Audit
  created_by            UUID REFERENCES auth.users(id),
  created_at            TIMESTAMPTZ DEFAULT now(),
  updated_at            TIMESTAMPTZ DEFAULT now(),
  UNIQUE(company_id, invoice_number)
);

CREATE INDEX idx_invoices_company ON suite.invoices(company_id);
CREATE INDEX idx_invoices_status  ON suite.invoices(status);
CREATE INDEX idx_invoices_buyer   ON suite.invoices(buyer_entity_id);

CREATE TABLE suite.invoice_line_items (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id      UUID NOT NULL REFERENCES suite.invoices(id) ON DELETE CASCADE,
  line_number     INT NOT NULL,
  product_id      UUID REFERENCES suite.products(id),  -- nullable; free-text allowed
  description     TEXT,
  hsn_code        TEXT,
  quantity        NUMERIC(15,3) DEFAULT 0,
  unit            TEXT DEFAULT 'KG',
  rate            NUMERIC(15,2) DEFAULT 0,
  amount          NUMERIC(15,2) DEFAULT 0,
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE suite.invoice_packing_lines (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  invoice_id      UUID NOT NULL REFERENCES suite.invoices(id) ON DELETE CASCADE,
  line_number     INT NOT NULL,
  marks_desc      TEXT,
  packages        INT DEFAULT 0,
  package_type    TEXT,
  gross_weight    NUMERIC(10,3) DEFAULT 0,
  net_weight      NUMERIC(10,3) DEFAULT 0,
  dimensions      TEXT,
  created_at      TIMESTAMPTZ DEFAULT now()
);

-- ════════════════════════════════════════════════════════════════
-- DASHBOARD AGGREGATIONS
-- Pre-computed KPIs. Suite reads these; never computes live.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE suite.kpi_snapshots (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id      UUID REFERENCES registry.companies(id),
  kpi_key         TEXT NOT NULL,    -- 'net_profit_mtd','cash_position','pending_approvals'
  kpi_value       NUMERIC,
  kpi_text        TEXT,
  kpi_json        JSONB,
  period          TEXT,             -- '2025-06' for monthly KPIs
  computed_at     TIMESTAMPTZ DEFAULT now(),
  UNIQUE(company_id, kpi_key, period)
);

CREATE TABLE suite.activity_feed (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id      UUID REFERENCES registry.companies(id),
  app             TEXT NOT NULL CHECK (app IN ('pramaana','clamflow','suite')),
  event_type      TEXT NOT NULL,
  event_summary   TEXT NOT NULL,
  entity_id       UUID,
  record_id       UUID,
  actor_id        UUID REFERENCES auth.users(id),
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_activity_feed_company ON suite.activity_feed(company_id);
CREATE INDEX idx_activity_feed_created ON suite.activity_feed(created_at);

-- ════════════════════════════════════════════════════════════════
-- SUITE AUDIT LOG
-- Same structure as registry.audit_log.
-- Tracks changes to suite.* tables only.
-- Append-only. No UPDATE or DELETE on this table ever.
-- ════════════════════════════════════════════════════════════════
CREATE TABLE suite.audit_log (
  id              BIGSERIAL PRIMARY KEY,
  company_id      UUID,
  schema_name     TEXT NOT NULL DEFAULT 'suite',
  table_name      TEXT NOT NULL,
  record_id       UUID,
  action          TEXT NOT NULL CHECK (action IN ('INSERT','UPDATE','DELETE')),
  old_data        JSONB,
  new_data        JSONB,
  changed_fields  TEXT[],
  user_id         UUID,
  user_email      TEXT,
  app             TEXT DEFAULT 'suite',
  created_at      TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_suite_audit_company ON suite.audit_log(company_id);
CREATE INDEX idx_suite_audit_created ON suite.audit_log(created_at);
